package BankACC_Assignment;

import java.util.InputMismatchException;
import java.util.Random;

import java.util.Scanner;

public class User {
	public static void main(String[] args) {
		
//		Account Creation
		int select;
		Scanner sc = new Scanner(System.in);
		BankAccount user = new BankAccount();
		System.out.println("---------- Welcome To 'The Success Banking' ----------");
		System.out.print("Create Your Account Name : ");
		user.holderName = sc.nextLine();
		System.out.print("Create Your PIN (4 Digits from 1000 - 9999) : ");
		user.pinNo = sc.nextInt();
		if(user.pinNo > 9999 || user.pinNo < 1000) {
			while(true) {
				System.err.println("Your PIN must be 4 digits(Numbers Only).");
				System.out.print("\nCreate Your PIN (4 Digits from 1000 - 9999) : ");
				user.pinNo = sc.nextInt();
				if(user.pinNo < 9999 && user.pinNo >= 1000) {
					break;
				}
			}
		}
		System.out.print("Create Your Password : ");
		user.password = sc.next();
		System.out.println("\n---------- Your Bank Account Number is Auto Generated by The System ----------");
		Random rand = new Random();
		int upperbound = 20000;
		user.accountNo = rand.nextInt(upperbound);
		System.out.println("Your Bank Account Number is  : " + user.accountNo +"\n");
		user.deposit(user.balance, sc);
		
//		Select Section
		select = 1;
		try {
			while(select != 0 ) {
				System.out.println("\n---------- Welcome To 'The Success Banking' ----------\n");
				System.out.println(  "           1 .   Show Information");
				System.out.println(  "           2 .   Deposit");
				System.out.println(  "           3 .   Withdraw");
				System.out.println(  "           4 .   Change Password");
				System.out.println(  "           0 .   Exit");
				
				System.out.print("Select to Continue : ");
				select = sc.nextInt();
				
				if(select < 0 || select > 4) {
					while(select < 0 || select > 4) {
						System.err.println("Please Only Select Between 0 to 4!");
						System.out.println("\n---------- Welcome To 'The Success Banking' ----------\n");
						System.out.println(  "           1 .   Show Information");
						System.out.println(  "           2 .   Deposit");
						System.out.println(  "           3 .   Withdraw");
						System.out.println(  "           4 .   Change Password");
						System.out.println(  "           0 .   Exit");
						System.out.print("Select to Continue : ");
						select = sc.nextInt();
					}
				}
				
				if(select == 0) {
					System.out.println("\n------------------------------ Program Ending ------------------------------------\n");
					break;
				}
				
				if(select == 1) {
					user.showInfo();
				}
				
				if(select == 2) {
					user.deposit(user.balance, sc);
				}
				
				if(select == 3) {
					user.withdraw(user.balance, sc);
				}
				
				if(select == 4) {
					user.changePassword(user.pinNo, sc);
				}
			}
		} catch (InputMismatchException e) {
			System.err.println("Invalid Choice.");
		}
		
		sc.close();
	}
}
